targets:
  $default:
    sources:
      - lib/**
      - graphql_queries/**
      - graphql.schema.json
    builders:
      artemis:
        options:
          schema_mapping:
            - schema: graphql.schema.json
              queries_glob: graphql_queries/*.graphql
              output: lib/graphql/graphql_api.dart
          scalar_mapping:
            - graphql_type: Long
              dart_type: int