targets:
  $default:
    sources:
      - lib/**
      - graphql_queries/**
      - schema.graphql
    builders:
      artemis:
        options:
          schema_mapping:
            - schema: schema.graphql
              queries_glob: graphql_queries/**.graphql
              output: lib/graphql/graphql_api.dart
          scalar_mapping:
            - graphql_type: Long
              dart_type: int
