name: ehrenamtskarte
description: App for the Bavarian Ehrenamtskarte owners.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0
  mapbox_gl: ^0.10.0
  provider: ^5.0.0
  graphql_flutter: ^4.0.1
  url_launcher: ^5.7.10
  maps_launcher: ^1.2.2+2
  flutter_svg: ^0.19.1
  package_info: ^2.0.0 # for about dialog
  qr_code_scanner: ^0.3.5
  flutter_secure_storage: ^4.0.0
  infinite_scroll_pagination: ^3.0.1
  geolocator: ^6.2.1
  flutter_launcher_icons: ^0.8.1
  mutex: ^2.0.0
  protobuf: ^2.0.0
  base32: ^1.1.2
  qr_flutter: ^3.2.0
  otp: ^2.2.3
  crypto: ^2.1.5
  intro_slider: ^2.3.4
  shared_preferences: ^0.5.12+4
  flutter_form_builder: ^5.0.0-alpha.1
  form_builder_image_picker: ^0.1.2
  tinycolor: ^1.0.3

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0

dependency_overrides:
  flutter_form_builder: ^5.0.0-alpha.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.15.7
  build_runner: ^1.10.4
  json_serializable: ^3.5.0
  effective_dart: ^1.3.0

  # graphQL type generation
  artemis: '>=6.0.0 <7.0.0' # only if you're using ArtemisClient!
  json_annotation: ^3.1.1
  equatable: ^1.2.6
  meta: '>=1.0.0 <2.0.0' # only if you have non nullable fields
  gql: '>=0.12.3 <1.0.0'

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
  image_path_ios: "assets/icon/icon.png"
  image_path_android: "assets/icon/icon.png"
  adaptive_icon_background: "assets/icon/icon_background.png"
  adaptive_icon_foreground: "assets/icon/icon_foreground.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/category_icons/
    - assets/detail_headers/
    - assets/eak-lettering.svg
    - assets/wappen-bavaria.png
    - assets/app_icon/
    - assets/icon/
    - assets/intro_slides/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
