language: dart
dist: focal
addons:
  apt:
    packages:
      - lib32stdc++6
env:
  global:
    # environment variable secretsJson, containing the content of frontend/secrets.json
    - secure: KBLrBZd6R+APLHgMcbiG6UjNKxOHDIqKFfc54oU7VWjIKzD57J59mFcPFe2aUPzXLt29+nZxOiiX4lJxQRx4YEBcrVcXujDcnOT+S6LxkYGYfLJQ3Id/aqKAyYeCdDu8sqGRV+KTLq3OGQfHnmnKSFLVyvMIkz+2SDPfs7lZz8djMtSFZst+EbOmWZ3iEzZzocd90/lbIRsyuNidAuY4QPlX/3rU0MFg6YcbwJWMoTq59pkFWlBMf7khx4OnwUqxDONjK5sRjGS/FU4K3d16o6SSibHAl+dsACHJbwY7XKGwE7zfauPOF2stIU1G8+3u0+7Sp0Re8yblyqfyRRUY0XbehcEIiJ1j6iy8j+i5NyfUKHWmqVAa9wpqLMsyUwuCc3lIdwcW0hWag+0M2oAGMsHsxWvwW/wTdu1Vm8lV0H6OObtQiq9gf71FJlK4Wj697rzOFgdQp0I+IvMHk+fr9zoscUGzN1KzIZcdpTULp+DXjFrgGxO2HBcmgkK2XeAe7x/2pBsteitw+6nTGH4+wXwNXfp2tj5ATsEkb0N2SrHGpyfVWnjcEOstVC5jrBaMIFv2VkPA/yNxXCoZSAK3tUoY3eOucYKvDbVyTuqfFIRu56XCiAAo50fW/tF/O+svyqYeM8MrZ2q1AmNTiOHS2IhgibAgCMFeib2LA9rOYyk=

stages:
  - test
  - build
  - name: deploy
    if: branch = main

jobs:
  include:
    - stage: test
      name: "Frontend flutter tests"
      install: scripts/setUpFlutter.sh
      script: cd frontend && ./flutter/bin/flutter test
      cache:
        directories:
          - $HOME/.pub-cache

    - stage: build
      name: "Build Android app"
      language: android
      dist: trusty
      android:
        components:
          - tools
          - platform-tools
          - build-tools-29.0.3
          - android-30
          - extra-android-m2repository
        licenses:
          - android-sdk-preview-license-.+
          - android-sdk-license-.+
      install:
        - tar -xf scripts/androidLicenses.tar -C /usr/local/android-sdk
        - scripts/setUpFlutter.sh
      script: cd frontend && ./flutter/bin/flutter build appbundle
      cache:
        directories:
          - $HOME/.pub-cache

    - name: "Build iOS app"
      os: osx
      osx_image: xcode12
      install: scripts/setUpFlutter.sh
      script: cd frontend && ./flutter/bin/flutter build ios --release --no-codesign
      cache:
        directories:
          - $HOME/.pub-cache