version: "3.5"
services:
  backend:
    build: ./backend/
    environment:
      - BACKEND_OPTS=-Dapp.postgres.url=jdbc:postgresql://db-postgis:5432/ehrenamtskarte -Dapp.postgres.user=postgres -Dapp.postgres.password=postgres
    depends_on:
      - db-postgis
    networks:
      - network
  reverse_proxy:
    image: "nginx:1.19.5"
    volumes:
      - ./map-tiles/styles:/usr/share/nginx/html
      - ./docker/reverse_proxy/nginx-staging.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 127.0.0.1:5002:80
    networks:
      - network_proxy
    depends_on:
      - martin
      - backend
networks:
  network_proxy:
    external:
      name: network
