version: "3.8"
services:
  db:
    image: "postgres:13.1"
    environment:
      - POSTGRES_DB=ehrenamtskarte
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
  adminer:
    image: "adminer:4.7.7-standalone"
    restart: always
    ports:
      - 5433:8080
