version: "3.3"
services:
  reverse_proxy:
    image: "nginx:1.19.5"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./docker/reverse_proxy/nginx-prod.conf:/etc/nginx/conf.d/default.conf
