steps:
  - run:
      name: Install Dart
      command: |
        curl -o dart.deb https://storage.googleapis.com/dart-archive/channels/stable/release/3.3.1/linux_packages/dart_3.3.1-1_amd64.deb
        sudo dpkg -i dart.deb