steps:
  - run:
      name: Install FVM
      command: |
        dart pub global activate fvm
        echo 'export PATH=$HOME/.pub-cache/bin:$PATH' >> $BASH_ENV
  - restore_cache:
      keys:
        - fvm-0-{{ checksum ".fvm/fvm_config.json" }}-{{ arch }}
  - run:
      name: Install Flutter
      command: fvm install
  - save_cache:
      key: fvm-0-{{ checksum ".fvm/fvm_config.json" }}-{{ arch }}
      paths:
        - .fvm
        - ~/fvm/
  - run:
      name: Show Flutter version
      command: fvm flutter --version
  - run:
      name: Configure Flutter
      command: fvm flutter config --no-analytics