description: Restores and saves fastlane cache of the passed directory.
parameters:
  directory:
    type: string
    default: native
steps:
  - restore_cache:
      keys:
        - 1-gems-{{ arch }}-{{ checksum "<< parameters.directory >>/Gemfile.lock" }}
        - 1-gems-{{ arch }}-
  - run:
      name: '[FL] install'
      command: bundle check || bundle install
      working_directory: << parameters.directory >>
  - save_cache:
      key: 1-gems-{{ arch }}-{{ checksum "<< parameters.directory >>/Gemfile.lock" }}
      paths:
        - << parameters.directory >>/vendor/bundle
