production: false
postgres:
  url: jdbc:postgresql://localhost:5432/ehrenamtskarte
  user: postgres
  password: postgres
map:
  #baseUrl: https://tiles.entitlementcard.app/rpc/physical_stores/{z}/{x}/{y}.pbf
  baseUrl: https://localhost:3000/rpc/physical_stores/{z}/{x}/{y}.pbf
geocoding:
  enabled: true
  host: nominatim.maps.tuerantuer.org
server:
  host: 0.0.0.0
  port: 8000
  dataDirectory: ./data
projects:
  - id: bayern.ehrenamtskarte.app
    importUrl: https://www.lbe.bayern.de/engagement-anerkennen/ehrenamtskarte/akzeptanzstellen/app-daten.xml
    pipelineName: EhrenamtskarteBayern
  - id: nuernberg.sozialpass.app
    importUrl: https://example.com
    pipelineName: SozialpassNuernberg
  - id: showcase.entitlementcard.app
    importUrl: https://example.com
    pipelineName: Showcase Berechtigungskarte
