production: false
postgres:
  url: jdbc:postgresql://localhost:5432/ehrenamtskarte
  user: postgres
  password: postgres
geocoding:
  enabled: true
  host: nominatim.maps.tuerantuer.org
server:
  host: 0.0.0.0
  port: 7000
  dataDirectory: ./data
projects:
  - id: bayern.ehrenamtskarte.app
    importUrl: https://www.lbe.bayern.de/engagement-anerkennen/ehrenamtskarte/akzeptanzstellen/app-daten.xml
    pipelineName: EhrenamtskarteBayern
  - id: nuernberg.sozialpass.app
    importUrl: https://example.com
    pipelineName: SozialpassNuernberg
  - id: showcase.entitlementcard.app
    importUrl: https://example.com
    pipelineName: Showcase Berechtigungskarte
