when: << pipeline.parameters.run_commit >>
jobs:
  - check
  - build_backend
  - pack_backend:
      requires:
        - build_backend
  - check_health_backend:
      requires:
        - pack_backend
  - check_frontend