when: << pipeline.parameters.run_commit >>
jobs:
  - bump_version:
        prepare_delivery: false
        context:
          - deliverino
  - check
  - check_backend
  - check_administration
  - check_frontend