when: << pipeline.parameters.run_deliver_beta_backend >>
jobs:
  - build_backend
  - build_martin
  - pack_backend:
      requires:
        - build_backend
  - check_health_backend:
      requires:
        - pack_backend
  - pack_martin:
      requires:
        - build_martin
  - pack_meta
  - deliver_backend:
      name: deliver_backend_staging
      production: false
      context:
        - credentials-ehrenamtskarte
      requires:
        - pack_backend
        - check_health_backend
        - pack_martin
        - pack_meta

