when: << pipeline.parameters.run_deliver_production_backend >>
jobs:
  - build_backend
  - build_martin
  - pack_backend:
      requires:
        - build_backend
  - check_health_backend:
      requires:
        - pack_backend
  - pack_martin:
      requires:
        - build_martin
  - pack_meta
  - deploy_backend:
      name: deploy_production
      server: entitlementcard.tuerantuer.org
      ssh-host-fingerprint: '|1|iikuvSrIo3wkj+EqUgLRMsAq6yk=|r9bSjkawWFa94b45qE/se5Oio5k= ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIED3MwobbCs+ENMLXdyqlJb3bJ26TuIYt977TA3NrN66'
      context:
        - entitlementcard-apt
      requires:
        - pack_backend
        - check_health_backend
        - pack_martin
        - pack_meta

