when: << pipeline.parameters.run_deliver_production_administration >>
jobs:
  - build_administration
  - pack_administration:
      requires:
        - build_administration
  - deliver_administration:
      name: deliver_administration_production
      production: true
      context:
        - credentials-ehrenamtskarte
      requires:
        - pack_administration

