version: 2.1

orbs:
  gradle: circleci/gradle@2.2.0
  browser-tools: circleci/browser-tools@1.4.1

parameters:
  run_commit:
    default: true
    type: boolean
  run_commit_main:
    default: true
    type: boolean
  run_deliver_beta_backend_administration:
    default: false
    type: boolean
  run_deliver_production_backend_administration:
    default: false
    type: boolean
  run_frontend:
    default: false
    type: boolean
  run_delivery_beta_native:
    default: false
    type: boolean
  run_delivery_production_native:
    default: false
    type: boolean
  run_promote_native:
    default: false
    type: boolean
  run_promote_backend_administration:
    default: false
    type: boolean