version: 2.1
orbs:
  gradle: circleci/gradle@2.2.0
workflows:
  default:
    jobs:
      - be-build
      - ad-build
      - be-pack:
          requires:
            - be-build
      - ad-pack:
          requires:
            - ad-build
      - meta-pack
      - styles-pack
      - martin-pack
      - deploy:
          requires:
            - be-pack
            - ad-pack
            - styles-pack
            - martin-pack
            - meta-pack
          filters:
            branches:
              only:
                - main

jobs:
  be-build:
    environment:
      # Configure the JVM and Gradle to avoid OOM errors
      _JAVA_OPTIONS: "-Xmx3g"
      GRADLE_OPTS: "-Dorg.gradle.daemon=false -Dorg.gradle.workers.max=2"
    docker:
      - image: circleci/openjdk:11.0.3-jdk-stretch
    working_directory: ~/project/backend
    steps:
      - checkout:
          path: ~/project
      - restore_cache:
          key: v2-gradle-wrapper-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}
      - restore_cache:
          key: v2-gradle-cache-{{ checksum "build.gradle.kts" }}
      - run: ./gradlew build
      - save_cache:
          paths:
            - .gradle/wrapper
          key: v2-gradle-wrapper-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}
      - save_cache:
          paths:
            - .gradle/caches
          key: v2-gradle-cache-{{ checksum "build.gradle.kts" }}
      - store_artifacts:
          path: build/libs
      - persist_to_workspace:
          root: ~/project
          paths:
            - backend/build/distributions/*

  ad-build:
    docker:
      - image: cimg/node:15.8.0
    working_directory: ~/project/administration
    steps:
      - checkout:
          path: ~/project
      - restore_cache:
          keys:
            - v1-node-modules-{{ checksum "package.json" }}-{{checksum "package-lock.json" }}
      - run:
          name: Install node dependencies
          command: "[ ! -d node_modules ] && npm ci --loglevel warn --yes || echo package.json and package-lock.json unchanged. Using cache."
      - run: npm run-script build
      - save_cache:
          paths:
            - node_modules
          key: v1-node-modules-{{ checksum "package.json" }}-{{checksum "package-lock.json" }}
      - store_artifacts:
          path: build
      - persist_to_workspace:
          root: ~/project
          paths:
            - administration/build

  be-pack:
    docker:
      - image: cimg/base:2020.01
    working_directory: ~/project/backend
    steps:
      - checkout:
          path: ~/project
      - attach_workspace:
          at: /tmp/workspace
      - run: ~/project/scripts/pack_deb.sh -v "0.$CIRCLE_BUILD_NUM" -t /tmp/workspace/backend/build/distributions/*.tar -s ~/project/scripts/eak-backend.service -d "Backend server for the Ehrenamtskarte app" -n "eak-backend" -c "default-jre"
      - run: |
          mkdir -p /tmp/artifacts/debs
          mv *.deb /tmp/artifacts/debs
      - store_artifacts:
          path: /tmp/artifacts
      - persist_to_workspace:
          root: /tmp/artifacts
          paths:
            - debs/*.deb

  ad-pack:
    docker:
      - image: cimg/base:2020.01
    working_directory: ~/project/administration
    steps:
      - checkout:
          path: ~/project
      - attach_workspace:
          at: /tmp/workspace
      - run: ~/project/scripts/pack_deb.sh -v "0.$CIRCLE_BUILD_NUM" -f /tmp/workspace/administration/build -d "Administration backend for the Ehrenamtskarte app" -n "eak-administration"
      - run: |
          mkdir -p /tmp/artifacts/debs
          mv *.deb /tmp/artifacts/debs
      - store_artifacts:
          path: /tmp/artifacts
      - persist_to_workspace:
          root: /tmp/artifacts
          paths:
            - debs/*.deb

  styles-pack:
    docker:
      - image: cimg/base:2020.01
    working_directory: ~/project/mapbox/styles
    steps:
      - checkout:
          path: ~/project
      - run:
          name: "Download glyphs"
          command: |
            wget -O /tmp/glyphs.zip https://github.com/orangemug/font-glyphs/archive/gh-pages.zip
            unzip /tmp/glyphs.zip
            mv font-glyphs* font-glyphs
            rm -f /tmp/glyphs.zip
      - run:
          name: "Build .deb"
          command: ~/project/scripts/pack_deb.sh -v "0.$CIRCLE_BUILD_NUM" -m . -d "Mapbox styles.json with dependencies for the Ehrenamtskarte app" -n "eak-styles"
      - run:
          name: "Move .deb to artifacts folder"
          command: |
            mkdir -p /tmp/artifacts/debs
            mv *.deb /tmp/artifacts/debs
      - store_artifacts:
          path: /tmp/artifacts
      - persist_to_workspace:
          root: /tmp/artifacts
          paths:
            - debs/*.deb

  martin-pack:
    docker:
      - image: cimg/base:2020.01
    working_directory: ~/project/mapbox/martin
    steps:
      - checkout:
          path: ~/project
      - run:
          name: "Download martin"
          command: |
            downloadUrl=$(curl -sH "Accept: application/vnd.github.v3+json" "https://api.github.com/repos/urbica/martin/releases/latest" | grep -o "http.*martin-Linux.*.tar.gz")
            echo "Downloding and extracting $downloadUrl …"
            wget -q -O- "$downloadUrl" | tar -xz
      - run:
          name: "Build .deb"
          command: ~/project/scripts/pack_deb.sh -v "0.$CIRCLE_BUILD_NUM" -d "Martin tile server for the Ehrenamtskarte app" -n "eak-martin" -s ~/project/scripts/eak-martin.service
      - run:
          name: "Move .deb to artifacts folder"
          command: |
            mkdir -p /tmp/artifacts/debs
            mv *.deb /tmp/artifacts/debs
      - store_artifacts:
          path: /tmp/artifacts
      - persist_to_workspace:
          root: /tmp/artifacts
          paths:
            - debs/*.deb

  meta-pack:
    docker:
      - image: cimg/base:2020.01
    working_directory: ~/project/administration
    steps:
      - checkout:
          path: ~/project
      - run: ~/project/scripts/pack_deb.sh -v "0.$CIRCLE_BUILD_NUM" -d "Meta package for the Ehrenamtskarte app" -n "eak" -c "eak-backend, eak-administration, eak-styles, eak-martin"
      - run: |
          mkdir -p /tmp/artifacts/debs
          cp *.deb /tmp/artifacts/debs
      - store_artifacts:
          path: /tmp/artifacts
      - persist_to_workspace:
          root: /tmp/artifacts
          paths:
            - debs/*.deb

  deploy:
    docker:
      - image: cimg/base:2020.01
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - add_ssh_keys:
          fingerprints:
            - "5c:8a:70:dc:61:9d:fa:c2:c2:6d:2d:fc:4a:ab:d2:e3"
      - run:
          name: "SFTP upload"
          command: |
            echo $APT_HOST_FINGERPRINT > known_hosts
            echo "Uploading: " /tmp/workspace/debs/*.deb
            sftp -b - -o UserKnownHostsFile=known_hosts ci@apt.ehrenamtskarte.app:/local-apt-repository/ \<<< "put -r /tmp/workspace/debs/*.deb"
